version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432 
      DB_DATABASE: proyectoB
      DB_USERNAME: postgres
      DB_PASSWORD: post123
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:latest
    container_name: crud-db
    ports:
      - "5433:5432"  # Puerto 5433 en el host mapeado al puerto 5432 del contenedor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post123
      POSTGRES_DB: proyectoB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: